name: coladaapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter_riverpod: ^1.0.1
  responsive_framework: ^0.1.5
  firebase_core: ^1.10.0
  flutter_svg: ^0.23.0+1
  auto_route: ^3.1.3
  pin_code_fields: ^7.3.0
  dartz: ^0.10.0
  dio: ^4.0.3
  loading_indicator: ^3.0.2
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.1.0+1
  qr_code_scanner: ^1.0.0
  map_picker: ^0.0.3
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.1
  geolocator: ^7.7.1
  overlay_support: ^1.2.1
  device_info: ^2.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  introduction_screen: ^2.1.0
  qr_flutter: ^4.0.0
  social_share: ^2.1.1
  intl: ^0.17.0
  country_code_picker: ^2.0.2
  shared_preferences: ^2.0.12
  webview_flutter: ^3.0.0
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.18
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - i18n/en.json
    - i18n/ar.json
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: SfPro
      fonts:
        - asset: assets/fonts/sf_pro.ttf
